### ISSUE TITLE
Error while pushing -- can you add the doc name/title to the error message?

### ISSUE THREAD

**Issue by JohnBergman** [Jumoo/uSync.Complete.Issues#119]
This is a screen shot of the error. (of course it'd be nice to get a fix for what happened as well)... but can you add the document title/name to the message so we know what was affected?

Also, after this error, does the process continue, or does it stop right there?

![image](https://user-images.githubusercontent.com/5505858/121556699-b95e8e00-c9d9-11eb-8e35-62ffa0fe3301.png)

**Comment by KevinJump** [comment]
HI Johm

the latest version does add the step name to this error so it gives a bit more of an issue - also this looks like an upload error - so its likely that either the upload failed due to file size or the zip failed - i would sort of expect a proper error if it was file size, 

but the v-latest version of uSync.Complete (8.10.1) contains a fix for unzipping files so i would hope this might fix this issue for you.

but if you want to confirm the error as to why the upload failed should be in the Umbraco logs of the server.

**Comment by JohnBergman** [comment]
Thanks!  I am upgrading right now.   We also had a lot of these in the log 

{"@t":"2021-06-10T15:29:15.0759078Z","@mt":"GetMediaFileStream : Media item {0} has no umbracoFile property","@l":"Warning","0":22734,"SourceContext":"uSync.Expansions.Core.Physical.SyncMediaFileService","ProcessId":1844,"ProcessName":"w3wp","ThreadId":22,"AppDomainId":2,"AppDomainAppId":"LMW3SVC8ROOT","MachineName":"MN-DEV-STLIHA01","Log4NetLevel":"WARN ","HttpRequestNumber":70,"HttpRequestId":"71148f67-2047-49c8-b736-13780c69758f"}
{"@t":"2021-06-10T15:29:15.0759078Z","@mt":"No media file stream to copy Media Id {Id}","@l":"Warning","Id":22734,"SourceContext":"uSync.Expansions.Core.Physical.SyncMediaFileService","ProcessId":1844,"ProcessName":"w3wp","ThreadId":22,"AppDomainId":2,"AppDomainAppId":"LMW3SVC8ROOT","MachineName":"MN-DEV-STLIHA01","Log4NetLevel":"WARN ","HttpRequestNumber":70,"HttpRequestId":"71148f67-2047-49c8-b736-13780c69758f"}
 
There were lots of these errors in the umbraco log too

**Comment by KevinJump** [comment]
humm. i wonder if that means the media items you are tring to get from the source are not there :( - as in you go to the media folder then look at an item does the media load ?

**Comment by JohnBergman** [comment]
That particular one seems to be there, its a PDF

**Comment by JohnBergman** [comment]
After the upgrade, we see this message...  What triggers this - I am pretty sure we have this configured right

![image](https://user-images.githubusercontent.com/5505858/121569792-c8980880-c9e6-11eb-80c2-31a3d952fc6f.png)

**Comment by KevinJump** [comment]
Hi, this is triggered if Umbraco is reporting as running as a replica (as in it returns `Umbraco.Core.Sync.ServerRole.Replica` as its state)

this happens when the Umbraco you are running is sharing its Database with another active (and running) version of Umbraco, when the sites start up one will be picked as the master and all others will be replicas.

if you have multiple servers serving your site, then only one should be the master and your should have a dedicated URL to access that site for the back office. 

the main issue to be aware of from a uSync point of view is the possibility of the underling server changing between requests (so if two or more servers answer to the same url). As uSync uses temp folders between requests, if the server changes then when the next request attempts to run things might be missing on disk. 

_(but there are also possible Umbraco side effects so you really shouldn't run this way unless you are sure of what you are doing)_

- if you are in dev/local dev and sharing a database and you know what you are doing you should be OK - but you need to be careful of servers overwriting each other.

**Comment by JohnBergman** [comment]
We have the class electing it to be a master for the backoffice.  I'll spend some time making sure that is the case.  Thanks for the insight.
