### ISSUE TITLE
v9: Publisher connection

### ISSUE THREAD

**Issue by PhyxionNL** [Jumoo/uSync.Complete.Issues#135]
**Describe the bug**
The connection test in Publisher doesn't show anything after "Connection Test : ", both for valid and invalid URLs.
Also the "Setup connection" button fails (shown in Umbraco UI) with: the URL returned a 404 (not found):
/umbraco/backoffice/usync/usyncpublishapi/setupServer

**Version (please complete the following information):**
 - Umbraco Version: 9 rc 2
 - uSync Version 9 rc 2
 - uSync.Complete Version 9 beta 5

**Comment by KevinJump** [comment]
HI, sorry for this -  but for later builds this functionalty is/has been removed - 

For the public beta it was still in there, but we have since taken the decision that we are not going to change appsettings from the UI (the new release will show you what to put where in the file, but it will not setup the server in the same way as v8 does

we do have later nightly builds on our public nightly server - but these are not super stable at the moment, but if you want to check things. :

https://pkgs.dev.azure.com/jumoo/Public/_packaging/nightly/nuget/v3/index.json
