### ISSUE TITLE
Question re uSync Publisher caching

### ISSUE THREAD

**Issue by LottePitcher** [Jumoo/uSync.Complete.Issues#161]
Hi Kevin,

Is the switching on and off of the uSync Publish cache persisted to the uSync.Publish.config file? I've switched it on in my local back office and don't think it updated the file, so not sure where/how this setting is stored.

It seems to me that switching on this cache would be a good idea. However I see it's disabled by default. Are there negative considerations of switching it on that we should consider? Otherwise it just seems a good idea to speed up the publishing process!

**Comment by KevinJump** [comment]
Hi, 

Its actually a setting in uSync8.config (because for behind the scenes reasons the cache isn't publisher specific) 

so in `uSync8.config` you should see 

```xml
<dependency>
  <publisherDependencyCache>True</publisherDependencyCache>
</dependency>
```

this turns it on. 

### Why it might be a good idea : 
with the cache on uSync will calculate the dependencies for an item when it is saved by Umbraco - so when you then do the push/pull the 'calculate' phase is super fast. 

### Potential downsides :
When on** The dependency check will perform on save/publish of all items in Umbraco - so if the item has a lot of dependencies it can be slow _(e.g a content item deep in a tree, with a content type with loads of compositions and properties)_

**but up until v8.11.7 (latest version) there was a bug #153 which mean the dependency check happens on save even when the cache is off 🤦 ,  **so actually if you turn it on it won't actually go any slower because as it stands its is already doing the check even when off.**

**Comment by LottePitcher** [comment]
Yes it was seeing those release notes that made me actually notice this feature for the first time...

Thanks for the reply, very helpful.
