### ISSUE TITLE
Error message typo and version mismatch

### ISSUE THREAD

**Issue by ianleeder** [Jumoo/uSync.Complete.Issues#194]
**Describe the bug**
One (or two) minor bugs.

First, I encountered a transient error when doing a sync.  Something along the lines of "Folder <guid> does not exist when it should", except it said "exsit".  I didn't grab a screenshot, and now I can't reproduce.  I'd search the repo and do a PR, except... private and all that.

Second, when going to log this issue, I thought I'd double-check my version.  Settings > uSync reports:  
![image](https://user-images.githubusercontent.com/8241300/217714662-4f2a34c9-96c3-4561-90ba-4cb89755ca03.png)

I'm not sure where v10.3.2 is coming from.  I have v10.4 installed:  
![image](https://user-images.githubusercontent.com/8241300/217714752-b2fad722-3ff7-4364-a083-6b349b7be291.png)

**Version (please complete the following information):**
 - Umbraco Version: 10.4.0
 - uSync Version: Nuget v10.4.0, uSync settings v10.3.2
 - uSync.Complete Version: v10.4.0

**To Reproduce**
Unknown, this was a transient error.  I retried and it's gone.

**Comment by KevinJump** [comment]
Hi, 

Yeah, the version 10.3.2 is for the uSync package which is at a different version then uSync.Complete (its complicated! but why we actually push the list so when debugging we can see). 

Its ok because uSync.Complete 10.4 required uSync 10.3.2 so they are all up to date.

Will/have fixed the typo for the next release. 

The Folder does not exist message can be a symptom of running in a load balanced environment, (uSync works when things are load balanced but you have makes sure requests between servers always hit the same server in the load balanced setup) 

might be worth a check. https://docs.jumoo.co.uk/usync/complete/Troubleshooting/connection
