### ISSUE TITLE
Usync complete to sync forms between envs

### ISSUE THREAD

**Issue by bielu** [Jumoo/uSync.Complete.Issues#206]
**Is your feature request related to a problem? Please describe.**
As developer I would like to be able to restore and push forms between envs with usage of usync complete.

**Describe the solution you'd like**
Being able to use publisher to send forms between envs.

**Comment by KevinJump** [comment]
Hi, 

uSync.Forms will do this if it is installed on a site with uSync.complete 

https://github.com/KevinJump/uSync.Forms

you should see the push and pull menu items appear on the forms menus. 

also if a form is referenced in a content item, then it should be picked up as a dependency and synced between sites.

**Comment by bielu** [comment]
Sadly I cannot see push and pull on forms menus 🤔 Is there any additional configuration for it?

**Comment by KevinJump** [comment]
shouldn't be - what versions do you have installed ?

**Comment by bielu** [comment]
```
    <PackageReference Include="Umbraco.Cms" Version="10.7.0" />
    <PackageReference Include="uSync.Complete" Version="10.7.1" />
    <PackageReference Include="uSync.Forms" Version="10.0.1" />
      <PackageReference Include="Umbraco.Forms" Version="10.5.0" />
```
Do you need any other informations?

**Comment by KevinJump** [comment]
Yeah - if the server is configured to push and pull (so you can see push and pull on the content tree) then it should also appear on the forms menus too. 

I've just tested this (although i installed Umbraco.Forms versions 10.5.1. because it didn't install on a new site properly).

And i got the menus 
![image](https://github.com/Jumoo/uSync.Complete.Issues/assets/431231/59972200-a3e8-4c1a-a8f3-b2175e425e67)

so the only diffrence here is i installed the lastes v10 version of forms, because the first time i tried i got a load of SQLite errors 

```xml
  <ItemGroup>
    <PackageReference Include="Umbraco.Cms" Version="10.7.0" />
    <PackageReference Include="Umbraco.Forms" Version="10.*" />
    <PackageReference Include="uSync.Complete" Version="10.7.1" />
    <PackageReference Include="uSync.Forms" Version="10.0.1" />
  </ItemGroup>
```

--- 

do you get any errors in the logs or in the browser when you right click on a form/the forms node ?

**Comment by bielu** [comment]
LOL updating to 10.5.1 fixed issue 😂
