### ISSUE TITLE
uSync will not push to environment if culture and hostnames are not set and language variants are not set on target environment

### ISSUE THREAD

**Issue by jvokesaztekweb** [Jumoo/uSync.Complete.Issues#223]
**Describe the bug**
I set up a multilingual umbraco site and wanted to push all of the pages and settings to my UAT environment but when I push I would get an error message saying the target culture does not exist. I am using uSkinned and am giving me Home and Global nodes unique culture and hostname names. It's only after I go to the target environment and add the language variant and then set culture and hostnames that uSync will then push to the environment. Shouldn't uSync push all settings including the language variant and culture and hostnames to the target environment?

**Version (please complete the following information):**
 - Umbraco Version: 10.4.0
 - uSync Version 10.3.2
 - uSync.Complete Version 10.4.0

**To Reproduce**
Create a multilingual site and set the culture and hostnames and then usync the site to the target environment that does not have language and culture and hostnames set.

**Expected behavior**
A migration of all pages per language to the target environment.

**Comment by KevinJump** [comment]
Hi, 

Yes it should (& you can push the languages from the settings page).

I will double check the version, but if 'Include dependencies' is set on the push it should go and fetch the languages and add them too. I remember fixing this in the last few months, but i can't remember if its only on v13 or on v10 too...

i will check.... 

work around on older / non-patched versions is to push the languages from the publisher server dashboard

**Comment by jvokesaztekweb** [comment]
Ok sounds good, please let me know if this is only a v10 issue or if this is fixed in v13. Thanks!

**Comment by KevinJump** [comment]
hI, 

Yes, this is something that has been fixed in v13. but its worth noting that even on v13. it only happens when you push content with 'include dependencies'

because languages are deamed to be settings, we don't push them, unless you are pushing the settings with the content and while this works, and many people do have it setup this way, we always suggest you sync settings etc seperatly from content just to give yourself control over those site wide elements when they change.
