### ISSUE TITLE
Permissions issue (potentially)

### ISSUE THREAD

**Issue by poornimanayar** [Jumoo/uSync.Complete.Issues#25]
I was testing uSync with user groups having access and landed up in a weird scenario. Here is some info

I have a master site which publishes out to a UK site and German site. 
I create a super users user group with access to usync publisher in default permissions
I choose not to add the super user group as allowed user group to my Germany or UK publisher settings.
In the CMS I do not see the usync publish options in the action menu, but I can see the publish to server

I dont know whether this is the expected result.

![image](https://user-images.githubusercontent.com/3941753/79966490-6a783100-8485-11ea-8823-7287caf7a165.png)

![image](https://user-images.githubusercontent.com/3941753/79967065-41a46b80-8486-11ea-856a-f3bc68fe1845.png)

![image](https://user-images.githubusercontent.com/3941753/79967103-51bc4b00-8486-11ea-9d59-ac7703b59944.png)

**Comment by KevinJump** [comment]
Not perfect :( 

if you have no servers configured then the actions will not show (because we can do some code behind stuff to work out the servers before rendering the button).

we don't do that for Publish to server - because well we are hacking Umbraco to get the button in, and when we do it we don't have access to some of the same properties. 

Did have a look before release but couldn't find a nice way of doing it.

should have had a known issue before release

**Comment by poornimanayar** [comment]
No worries Kevin. As I said I wasn't sure myself either as permissions can get really tricky and play with your head. So the issue was a way to reflect it.

**Comment by KevinJump** [comment]
Hi,

We are just cleaning up old, issues, i hope this was something that has either been fixed for you or not happened again. 
if this is still an issue, then feel free to drop in a comment and we will look at re-opening the issue. 

♾️
