### ISSUE TITLE
Timeout when pushing large amount of content

### ISSUE THREAD

**Issue by ykkp2000** [Jumoo/uSync.Complete.Issues#87]
Hi,

I've upgraded to latest 8.9.1, and trying to push a node that has about 500 descendents, and getting this error: 
Error while processing Push - (Action: import/5/2/) - https://v8-/umbraco/uSyncReceive/uSyncReceiveApi/ImportPackSecondPass timed out to after 100009ms

This looks like it could the standard HttpClient timeout, am I missing a config somewhere? Or is it a bug? Has anyone else encountered this?

**Comment by KevinJump** [comment]
Hi,

It is a standard timeout but there is a chance. it timed out because the process crashed on the target site.

We are trying to workout the best way to help debug this issue. when this happens is the UI still updating just before it times out (e.g are the names of the items being updated changing, or does it look 'frozen'?)

also are their any errors on the target server - there might be an error in the logs on the server you are pushing to, that might indicate what is going on.

**Comment by KevinJump** [comment]
Hi, 

one mitigation that might work is to change the number of items that are processed at any one time. 

within the uSync.Publisher.Config file. you can set a pageSize e.g

```xml
<uSyncPublisher incomingEnabled="true" outgoingEnabled="true">
	<pageSize>10</pageSize>
          ... rest of the file
</uSyncPublisher>
```
(you will need to restart the umbraco site after this change).

This should change the amount of items sent in each request (the default is 50) so if you have a site with very long publish times this might help.

**Comment by ykkp2000** [comment]
Hi,

Thanks for your thoughts, I'm a bit baffled as to what's going on the destination server, looking at the logs, the new content seems to be triggering a job within the SeoChecker plugin, that's erroring when validating html. This is then causing a sql timeout, which in turn is ruining my day! 
Will need to investigate further.
